# Allow other peers to connect to this server.
#
[peer_ip]
0.0.0.0

[peer_port]
51235

# Allow untrusted clients to connect to this server.
#
[websocket_public_ip]
0.0.0.0

[websocket_public_port]
5006

# Provide trusted websocket ADMIN access to the localhost.
#
[websocket_ip]
127.0.0.1

[websocket_port]
6006

# Provide trusted json-rpc ADMIN access to the localhost.
#
[rpc_ip]
127.0.0.1

[rpc_port]
5005

[rpc_allow_remote]
0

[node_size]
tiny

[ledger_history]
256

# Note that HyperLevelDB is unavailable on Windows platforms
#
[node_db]
type=HyperLevelDB
path=/var/lib/rippled/hyperldb

[database_path]
/var/lib/rippled

#[debug_logfile]
#log/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

# Where to find some other servers speaking the Ripple protocol.
# This set of addresses is recent as of September 5, 2013
#
[ips]
54.225.112.220 51235
54.225.123.13  51235
54.227.239.106 51235
107.21.251.218 51235
184.73.226.101 51235
23.23.201.55   51235


# I remember having trouble with this, might work just fine though.
#[validators_site]
#ripple.com

# Instead, provide a manual list of validators
[validators]
n9KPnVLn7ewVzHvn218DcEYsnWLzKerTDwhpofhk4Ym1RUq4TeGw
n9LFzWuhKNvXStHAuemfRKFVECLApowncMAM5chSCL9R5ECHGN4V
n94rSdgTyBNGvYg8pZXGuNt59Y5bGAZGxbxyvjDaqD9ceRAgD85P
n9LeQeDcLDMZKjx1TZtrXoLBLo5q1bR1sUQrWG7tEADFU6R27UBp
n9KF6RpvktjNs2MDBkmxpJbup4BKrKeMKDXPhaXkq7cKTwLmWkFr

# This is totally necessary.
[validation_quorum]
3

